# Site settings
title: "Bailey Burnsed"
email: bburnsed1995@gmail.com
description: "A blog about a Aspie Nerd/FullStack Developer."
baseurl: ""
url: "https://www.baileyburnsed.dev"
title_description: "I am Bailey Burnsed, I am a self taught software developer and student, 
I am a passionate programmer and I love to develop applications and games with the Flutter, Vuejs and Godot Game engine, using Firebase and the MEVN, and 
Lamp stacks."
title_image: "https://secure.gravatar.com/avatar/95ca0276401807bd839003f4577d4a3f"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Burnsedia3dArt
github_username:  Burnsedia
instagram_username:
linkedin_link: https://www.linkedin.com/in/bailey-burnsed-50051115a/
facebook_link: https://www.facebook.com/profile.php?id=100006610295406

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
