[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24.2.0"
  PUBLIC_GA_ID = "G-LRMSZ4V1XG"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline';
      connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://www.googletagmanager.com;
      img-src 'self' data: https://www.google-analytics.com;
    """

